### ISSUE TITLE
'MethodResultWrapper' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?)

### ISSUE THREAD

**Issue by maxiaodegithub** [MasayukiSuda/flutter_nfc_mynumber#1]
flutter_nfc_mynumber-0.0.7\android\src\main\kotlin\com\daasuu\flutter_nfc_mynumber\FlutterNfcMynumberPlugin.kt: (158, 11): Class 'MethodResultWrapper' is not abstract and does not implement abstract member public abstract fun error(p0: String, p1: String?, p2: Any?): Unit defined in io.flutter.plugin.common.MethodChannel.Result

**Comment by and2long** [comment]
I have fix this issue.
U can try this now before author merge my PR.
```
flutter_nfc_mynumber:
    git:
      url: https://github.com/and2long/flutter_nfc_mynumber.git
      ref: main
```
